global:
  scrape_interval: 5s 

  external_labels:
    monitor: 'study_monitor'


scrape_configs:

  - job_name: computer_metrics'
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http

    static_configs:
      - targets: ['192.168.2.116:9100']

  - job_name: study_metrics'
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http

    static_configs:
      - targets: ['192.168.2.116:3000']